### ISSUE TITLE
`/objects` doc review

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/docs#29]
`/objects` doc is obsolete and refers to BE3 :scream: 

What's needed:
 * new index od `/objects` reference
 * usually only `GET /objects?...` as index is recommended, to get a single item `GET /{type_name}/{id}` form is recommended
* `DELETE /objects/{id}`  is ok
* POST and PATCH are performed only on  `/{type_name}` where `{type_name}` is not abstract

**Comment by didoda** [comment]
PR available [https://github.com/bedita/docs/pull/39]... after merge this issue can be closed

**Comment by didoda** [comment]
Done with #39
