### ISSUE TITLE
/folders endpoint w filters and parent/children relations

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/docs#33]
* [#1506](https://github.com/bedita/bedita/pull/1506) #1495 permanent remove folder
* [#1484](https://github.com/bedita/bedita/issues/1484) Folder children ordering
* [#1431](https://github.com/bedita/bedita/issues/1431) Folder API write operations
* [#1451](https://github.com/bedita/bedita/pull/1451) #1431 GET /folders/:id/parent is here

**Comment by didoda** [comment]
PR available [https://github.com/bedita/docs/pull/37]... after merge this issue can be closed

**Comment by didoda** [comment]
Done with #37
